### ISSUE TITLE
ImportError: cannot import name 'perceptual_loss'

### ISSUE THREAD

**Issue by AKclown** [sicxu/Deep3DFaceRecon_pytorch#1]
Hello, I followed the instructions provided by the readme to debug the demo, and the following error occurred. How to solve this problem, can you give me some suggestions?

The platform is window10

![image](https://user-images.githubusercontent.com/33648653/126282464-ef26343b-4313-485d-9daa-30c227f3e283.png)

**Comment by YuDeng** [comment]
Hi, this released version has not been tested on Windows 10. Can you try to run demo.py under linux environment?

**Comment by AKclown** [comment]
Unfortunately, currently I only have a window system. I use Deep3DFaceReconstruction first, thank you for your reply

**Comment by YuDeng** [comment]
Sorry for the inconvenience. We will try to fix the bug and test the code under Windows.

**Comment by zhoushiwei** [comment]
> Sorry for the inconvenience. We will try to fix the bug and test the code under Windows.

I have the same error on Mac

**Comment by japonica99** [comment]
This problem is solvable, I encountered a similar problem to yours. The main reason is that when you copy the insightface in windows, you may have overwritten the loss file in the models folder, it is recommended to check if the functions mentioned in the error are in the loss file, if not, just download it from the repository and overwrite it. arcface should be put in one folder, it should not overwrite the original The python files under the models file should not be overwritten.
