### ISSUE TITLE
Question about 

### ISSUE THREAD

**Issue by cnnAndBn** [sicxu/Deep3DFaceRecon_pytorch#111]
hi:
   thanks for your excellent work, am new to face related work. Have a naive question,here
https://github.com/sicxu/Deep3DFaceRecon_pytorch/blob/6f28de21539f186b9e8ea18d331c6d90cd696006/util/preprocess.py#L127
what is BBRegressorParam_r.mat for? 
another one is https://github.com/sicxu/Deep3DFaceRecon_pytorch/blob/6f28de21539f186b9e8ea18d331c6d90cd696006/util/preprocess.py#L42
what is this function for? can you give some paper related to it? @sicxu 
thanks a lot

**Comment by sicxu** [comment]
Hi, this function is designed to output a bounding box from 5 facial points. Then we can use this bounding box to crop input image for 68 facial landmark detection. There is no related paper about this function. You can regard this as a hack to process the input image.

I can give you a brief explanation of this function. Suppose we have the ground truth 68 landmarks, then we can compute a bounding box based on these points. However, when we want to test a input, we cannot get the 68 points at the beginning. So we just use the 5points and the bounding box from 68 points as training pairs, then we simply do something like linear regression to get this mapping. Since our training process for the landmark detector involves lots of data augmentation, so this rough bounding box is sufficient enough for inference.
