### ISSUE TITLE
The training data discrepency

### ISSUE THREAD

**Issue by coloss** [sicxu/Deep3DFaceRecon_pytorch#59]
In your readme you mention that the provided model was trained on a combination of CelebA, LFW, 300WLP, IJB-A, LS3D-W, and FFHQ but your instructions for training only mention FFHQ. 

Can we expect reduced performance when training according to these instruction and using FFHQ only?

**Comment by sicxu** [comment]
In our training instruction, we say that we used an "extra" rather than "only" dataset compared to the original tensorflow implementation.

We use **_an extra_** high quality face image dataset [FFHQ](https://github.com/NVlabs/ffhq-dataset)[](https://github.com/sicxu/Deep3DFaceRecon_pytorch#requirements) to increase the diversity of training data.
